name: Build .NET Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      DOTNET_ROOT: C:\Program Files\dotnet
      Configuration: Debug
      Solution_Name: BooksAndFractals.sln  # <-- Change to your actual solution name

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'  # or whatever version your project uses

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build solution
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore
